<a href="https://colab.research.google.com/github/Anonymousundefined/ML/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
print("hello anmol11122")

hello anmol11122


In [ ]:
a=np.array([[1,1,2],[1,2,1]],np.int64)

In [ ]:
a

array([[1, 1, 2],
       [1, 2, 1]])

In [ ]:
b=np.zeros((2,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a.size


6

In [ ]:
a.shape

(2, 3)

In [ ]:
a

array([[1, 1, 2],
       [1, 2, 1]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
c=np.arange(44)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [ ]:
g=np.empty((4,6))
g

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
 k=np.identity(4)
 k

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

FUNCTIONS

In [ ]:
k.ravel()

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [ ]:
k.reshape(8,2)

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [ ]:
k1=np.linspace(1,4,10)

In [ ]:
k1

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [ ]:
k1[1]

1.3333333333333333

### axis concept

In [ ]:
x=[[1,1,1],[211,1,1],[3,0,0]]
y=np.array(x)
y

array([[  1,   1,   1],
       [211,   1,   1],
       [  3,   0,   0]])

In [ ]:
y.sum()

219

In [ ]:
y.sum(axis=0)

array([215,   2,   2])

In [ ]:
y.T

array([[  1, 211,   3],
       [  1,   1,   0],
       [  1,   1,   0]])

In [ ]:
y.ndim

2

In [ ]:
y.nbytes

72

In [ ]:
 a1=np.array([1,2,3,4])
 a1.argmax()

3

In [ ]:
a1.argsort()

array([0, 1, 2, 3])

In [ ]:
y.argmin(axis=0)

array([0, 2, 2])

In [ ]:
y

array([[  1,   1,   1],
       [211,   1,   1],
       [  3,   0,   0]])

In [ ]:
z=np.array([[1,1,1],[1,1,1],[2,2,2]] )
z

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
y+z

array([[  2,   2,   2],
       [212,   2,   2],
       [  5,   2,   2]])

In [ ]:
y*z

array([[  1,   1,   1],
       [211,   1,   1],
       [  6,   0,   0]])

In [ ]:
y+(z*y)+(y*y)

array([[    3,     3,     3],
       [44943,     3,     3],
       [   18,     0,     0]])

In [ ]:
np.sqrt(y)

array([[ 1.        ,  1.        ,  1.        ],
       [14.52583905,  1.        ,  1.        ],
       [ 1.73205081,  0.        ,  0.        ]])

In [ ]:
y

array([[  1,   1,   1],
       [211,   1,   1],
       [  3,   0,   0]])

In [ ]:
np.where(y==1)

(array([0, 0, 0, 1, 1]), array([0, 1, 2, 1, 2]))

In [ ]:
import sys

In [ ]:
ab=[1,2,3]
sys.getsizeof(1)*len(ab)


84

In [ ]:
ab1=np.array(ab)
ab1.itemsize*ab1.size

24